### PR TITLE
fix: api.md html snippet render error fix.

### PR DESCRIPTION
**Pull request by billfeller**
1. use &lt;codehtml/> instead of &lt;code/>  in html snippet.
2. use {/*  */} instead of &lt;!-- --> in html snippet.

### CODE REVIEW

**Comment by frehner** [comment]
I’m good with the change to comments

But would like to keep the code different from normal text. Since this is markdown, we should be able to use backticks to replace it, right?

**Comment by billfeller** [comment]
yeah, i have tried backticks yet, but it can not be rendered in html snippet as below.

image

i try &lt;b> as below, it look good enough to emphasize the words.

image

which one to choose, backticks or &lt;b>

**Comment by internettrans** [comment]
Might be best to switch off of html entirely and just use markdown

**Comment by frehner** [comment]
An alternative would be to add a class to `code` blocks that allows them to either be as they are or optionally an inline block of text (like what is desired here). I think @filoxo is the one that originally did the work on this - thoughts?

**Comment by internettrans** [comment]
I actually think it was @alocke12992 who might have put this documentation together. Not entirely sure

**Comment by frehner** [comment]
> I actually think it was @alocke12992 who might have put this documentation together. Not entirely sure

I meant @filoxo was the person that originally coded/styled the `code` tags I believe.

**Comment by billfeller** [comment]
i try to extend `src/theme/MDXComponents` to use &lt;code/>. so it need to use &lt;codehtml/>in html snippet instead, then we can use originally coded/styled.

image

i just use swizzle the [theme-components](https://v2.docusaurus.io/docs/using-themes/#swizzling-theme-components) and extend with codehtml.  68549fba1a60e75794139c883d1e035e4a7242af

@frehner @joeldenning

**Comment by billfeller** [comment]
```suggestion
  codehtml: props => {
    const {children} = props;
    return <code>{children}</code>
  },
```

**Review by frehner — APPROVED** [review]
That looks great, thanks for your work on this!

**Pull request merged**
