### PR TITLE
Fix redirects

### PR DESCRIPTION
**Pull request by lex111**
Demo build - https://build-jb3zykk1v.now.

Finally it should work correctly, at least there are no problems on the demo website, please see.

cc @frehner

### CODE REVIEW

**Comment by frehner** [comment]
code looks good to me

demo site is dead.

**Comment by lex111** [comment]
Correct link - https://build-jb3zykk1v.now.sh/

**Comment by frehner** [comment]
thanks again

**Comment by lex111** [comment]
@frehner unfortunately, the issue has not been resolved (yes, yes, it also annoys me already!). I think the matter is in the hosting provider, because now the redirects work fine in Now Zeit, and something goes wrong on the GitHub Pages.
But in fact, you correctly proposed a solution in https://github.com/CanopyTax/single-spa.js.org/pull/119/files
I can’t come up with the best yet, but yours works at 100%.

**Comment by lex111** [comment]
https://github.com/CanopyTax/single-spa.js.org/pull/121/files

**Pull request merged**
