### PR TITLE
Add documentation for solving TLS errors

### PR DESCRIPTION
**Pull request by internettrans**
See related https://github.com/single-spa/create-single-spa/pull/267

### CODE REVIEW

**Review by frehner — APPROVED** [review]
ten years later.... approved :D

**Comment by internettrans** [comment]
The create-single-spa pull request hasn't been merged, as there was discussion over what would be the best approach. So this documentation is pending the work in create-single-spa.

**Comment by frehner** [comment]
Approval REVOKED then! Mainly just to make it easier to remember why it isn't merged. :)

**Comment by internettrans** [comment]
Going to close this as I don't think the create-single-spa side of this was ever merged.

**Pull request closed without merging**
