### PR TITLE
Update curly braces for HTML representation

### PR DESCRIPTION
**Pull request by mstrlaw**
Fixes curly braces not showing up on render.

### CODE REVIEW

**Review by frehner — APPROVED** [review]
Thanks!

does this fix #196 completely ?

**Comment by mstrlaw** [comment]
I only found one instance of that within _api.md_. Created the issue asap in order not to forget about it.

Should I create an issue for these minor things or just do a PR straight up?

**Comment by internettrans** [comment]
PR without issue is fine

**Comment by frehner** [comment]
whoops I meant #193 

I'll go close that now.

**Pull request merged**
