### PR TITLE
Adds note about workaround for Angular Router (v4)

### PR DESCRIPTION
**Pull request by jualoppaz**

### CODE REVIEW

**Comment by internettrans** [comment]
Like I said in #160, I don't think this information is specific to Angular 4/5 and should just be part of the regular docs instead of specific to a version

**Comment by jualoppaz** [comment]
V4 refers to single-spa docs version and not to Angular Router. Sorry for the confusion.

**Review by internettrans — APPROVED** [review]
Ah my mistake - thanks for this. Btw you can modify more than one file at a time if you fork and clone this repo, then push up the code from your computer.

**Comment by jualoppaz** [comment]
Ok @joeldenning . I'll have it in mind this next time. Thanks.

**Pull request merged**
