### PR TITLE
Adds single-spa example of Option 2: NPM packages (v4)

### PR DESCRIPTION
**Pull request by jualoppaz**
Adds a single-spa example that shows how to setup Option 2: NPM packages strategy for splitting applications

### CODE REVIEW

**Review by internettrans — CHANGES_REQUESTED** [review]
👍 thanks. Can you also add this to the v5 docs (they are pending release). The file to modify is https://github.com/single-spa/single-spa.js.org/blob/master/docs/separating-applications.md. We will be releasing v5 relatively soon

**Comment by jualoppaz** [comment]
@joeldenning here you have: https://github.com/single-spa/single-spa.js.org/pull/153 . I tried to edit it directly from docs page and I supposed that I was editing master instead of v4 docs.

This is very minimalist example. I'll improve it along next week

**Review by internettrans — APPROVED** [review]
👍 thanks. Your work creating the example is appreciated.

**Comment by jualoppaz** [comment]
@joeldenning thanks to you. We are starting using single-spa in my job and this dedication has been very good for me 😉

**Pull request merged**
