### PR TITLE
Adding documentation about Module Federation.

### PR DESCRIPTION
**Pull request by internettrans**
image

### CODE REVIEW

**Review by TheMcMurder — APPROVED** [review]
This looks good. Hopefully this will help people choose an approach. I’m surprised at how so many people are excited about module federation instead of the import map approach. As far as I’m aware there isn’t a compelling reason to choose module federation over import maps 🤷🏼‍♂️

**Comment by TheMcMurder** [comment]
> image
> 
> 

Thanks for including the screen shot. It made it much easier to review.

**Comment by frehner** [comment]
The advantage I see is that this still provides a way to have “standalone” apps. 

How often people will use that in practice I’m not sure though

**Comment by internettrans** [comment]
I think people like standalone apps for development, but not for production. Might be worthwhile adding it to the docs, though

**Pull request merged**
